CREATE TABLE user_profile
(
  ID         UUID NOT NULL,
  IDAM_ID    VARCHAR(120) NOT NULL,
  EMAIL      VARCHAR(120) NOT NULL,
  FIRST_NAME VARCHAR(80) NOT NULL,
  LAST_NAME  VARCHAR(80) NOT NULL,

  PRIMARY KEY (ID)
);