CREATE TABLE user_profile
(
  ID                         UUID         NOT NULL,
  EMAIL                      VARCHAR(255) NOT NULL UNIQUE,
  FIRST_NAME                 VARCHAR(255) NOT NULL,
  LAST_NAME                  VARCHAR(255) NOT NULL,
  LANGUAGE_PREFERENCE        VARCHAR(255) NOT NULL,
  EMAIL_COMMS_CONSENT        BOOLEAN      NOT NULL DEFAULT FALSE,
  EMAIL_COMMS_CONSENT_TS     TIMESTAMP,
  POSTAL_COMMS_CONSENT       BOOLEAN      NOT NULL DEFAULT FALSE,
  POSTAL_COMMS_CONSENT_TS    TIMESTAMP,
  USER_CATEGORY              VARCHAR(255) NOT NULL,
  USER_TYPE                  VARCHAR(255) NOT NULL,
  EXTENDED_ATTRIBUTES        JSON,
  IDAM_STATUS                VARCHAR(255),
  IDAM_REGISTRATION_RESPONSE SMALLINT,
  CREATED_TS                 TIMESTAMP    NOT NULL,
  LAST_UPDATED_TS            TIMESTAMP    NOT NULL,

  PRIMARY KEY (ID)
);